'use client'

import { useState } from 'react'
import { cn } from '@/lib/utils'
import type { SeriesPoint } from '@/lib/finance/series'

// Same unit on every series, so they share one axis. Two y-scales would invent
// a relationship that is not in the data.
const SERIES = [
  { key: 'income'  as const, label: 'Income',   color: 'var(--chart-income)' },
  { key: 'net'     as const, label: 'Net',      color: 'var(--chart-1)' },
  { key: 'expense' as const, label: 'Expenses', color: 'var(--chart-expense)' },
]

const W = 640
const H = 240
const PAD = { top: 16, right: 74, bottom: 28, left: 56 }

function compact(n: number): string {
  const abs = Math.abs(n)
  const sign = n < 0 ? '-' : ''
  if (abs >= 1_000_000) return `${sign}$${(abs / 1_000_000).toFixed(1)}M`
  if (abs >= 1_000) return `${sign}$${Math.round(abs / 1_000)}k`
  return `${sign}$${Math.round(abs)}`
}

function full(n: number): string {
  return new Intl.NumberFormat('en-US', {
    style: 'currency', currency: 'USD', maximumFractionDigits: 0,
  }).format(n)
}

/**
 * Axis ticks on clean round numbers, always spanning the whole data range.
 *
 * The range has to be covered, not merely approached: the previous version
 * stopped at the last round number below the maximum, so a peak above it was
 * plotted above the plot area and clipped by the viewBox — the top of the line
 * was simply cut off.
 */
function niceTicks(min: number, max: number, count = 4): number[] {
  const span = max - min || Math.abs(max) || 1
  const raw = span / count
  const mag = 10 ** Math.floor(Math.log10(raw))
  const step = [1, 2, 2.5, 5, 10].map((m) => m * mag).find((s) => s >= raw) ?? mag * 10
  const start = Math.floor(min / step) * step
  const end = Math.ceil(max / step) * step
  const ticks: number[] = []
  // Generated by index rather than by accumulation, so repeated addition of a
  // fractional step cannot drift the labels off their round numbers.
  for (let i = 0; start + i * step <= end + step / 1000; i++) ticks.push(start + i * step)
  return ticks
}

/**
 * Income, net and expenses as lines over the charted months.
 *
 * The bar view answers "what did each month look like"; this one answers "which
 * way is it going", which columns are poor at — comparing bar heights across
 * six months is exactly the job a line does better.
 *
 * Net is the reason the chart exists, so it takes the accent while income and
 * expenses keep the green/red they carry everywhere else. That pair measures
 * ΔE 7.2 under protanopia, which is only legal alongside secondary encoding:
 * every line is labelled at its end, the legend is always present, and the
 * table below the chart carries every value.
 */
export function TrendChart({
  data,
  cumulative = false,
}: {
  data: SeriesPoint[]
  /** Values are running totals across the window rather than per-month. */
  cumulative?: boolean
}) {
  const [hover, setHover] = useState<number | null>(null)

  if (data.length < 2) {
    return (
      <p className="py-6 text-center text-sm text-muted-foreground">
        Not enough months to plot a trend yet.
      </p>
    )
  }

  const values = data.flatMap((d) => [d.income, d.expense, d.net])
  const rawMax = Math.max(...values, 0)
  const rawMin = Math.min(...values, 0)
  const ticks = niceTicks(rawMin, rawMax)
  const yMin = Math.min(...ticks, 0)
  const yMax = Math.max(...ticks)

  const plotW = W - PAD.left - PAD.right
  const plotH = H - PAD.top - PAD.bottom
  const x = (i: number) => PAD.left + (i / (data.length - 1)) * plotW
  const y = (v: number) => PAD.top + plotH - ((v - yMin) / (yMax - yMin || 1)) * plotH

  // End labels, pushed apart when lines converge so none sits on top of another.
  const ends = SERIES
    .map((s) => ({ ...s, value: data[data.length - 1][s.key], yPos: y(data[data.length - 1][s.key]) }))
    .sort((a, b) => a.yPos - b.yPos)
  const MIN_GAP = 14
  for (let i = 1; i < ends.length; i++) {
    if (ends[i].yPos - ends[i - 1].yPos < MIN_GAP) {
      ends[i].yPos = ends[i - 1].yPos + MIN_GAP
    }
  }

  const active = hover != null ? data[hover] : null
  const labelEvery = Math.max(1, Math.ceil(data.length / 8))

  return (
    <div className="flex flex-col gap-3">
      <div className="relative">
        <svg
          viewBox={`0 0 ${W} ${H}`}
          className="h-auto w-full"
          role="img"
          aria-label={
            cumulative
              ? 'Income, net and expenses accumulated month by month across the charted window. The same values are listed in the table below.'
              : 'Income, net and expenses by month. The same values are listed in the table below.'
          }
          onPointerLeave={() => setHover(null)}
          onPointerMove={(e) => {
            const r = e.currentTarget.getBoundingClientRect()
            const px = ((e.clientX - r.left) / r.width) * W
            const i = Math.round(((px - PAD.left) / plotW) * (data.length - 1))
            setHover(Math.max(0, Math.min(data.length - 1, i)))
          }}
        >
          {/* Gridlines: solid hairlines one step off the surface, never dashed. */}
          {ticks.map((t) => (
            <g key={t}>
              <line
                x1={PAD.left} x2={W - PAD.right} y1={y(t)} y2={y(t)}
                stroke={t === 0 ? 'var(--muted-foreground)' : 'var(--border)'}
                strokeOpacity={t === 0 ? 0.5 : 1}
                strokeWidth={1} vectorEffect="non-scaling-stroke"
              />
              <text
                x={PAD.left - 8} y={y(t)} dy="0.32em" textAnchor="end"
                className="fill-muted-foreground" style={{ fontSize: 11 }}
              >
                {compact(t)}
              </text>
            </g>
          ))}

          {/* Crosshair — readers aim at a month, never at a 2px line. */}
          {hover != null && (
            <line
              x1={x(hover)} x2={x(hover)} y1={PAD.top} y2={PAD.top + plotH}
              stroke="var(--muted-foreground)" strokeOpacity={0.35}
              strokeWidth={1} vectorEffect="non-scaling-stroke"
            />
          )}

          {SERIES.map((s) => (
            <path
              key={s.key}
              d={data.map((d, i) => `${i === 0 ? 'M' : 'L'}${x(i).toFixed(1)} ${y(d[s.key]).toFixed(1)}`).join(' ')}
              fill="none" stroke={s.color} strokeWidth={2}
              strokeLinecap="round" strokeLinejoin="round"
              vectorEffect="non-scaling-stroke"
            />
          ))}

          {/* Markers on the hovered month, ringed in the surface so they stay
              legible where two lines cross. */}
          {hover != null && SERIES.map((s) => (
            <g key={s.key}>
              <circle cx={x(hover)} cy={y(data[hover][s.key])} r={5} fill="var(--card)" />
              <circle cx={x(hover)} cy={y(data[hover][s.key])} r={3} fill={s.color} />
            </g>
          ))}

          {/* Direct end labels: the secondary encoding that makes the green/red
              pair legible for readers who cannot tell those hues apart. */}
          {ends.map((s) => (
            <text
              key={s.key}
              x={W - PAD.right + 8} y={s.yPos} dy="0.32em"
              className="fill-foreground" style={{ fontSize: 11, fontWeight: 500 }}
            >
              {s.label}
            </text>
          ))}

          {/* Thinned so a month plotted by day does not print thirty
              overlapping labels. The first and last are always kept, so the
              span the chart covers is never ambiguous. */}
          {data.map((d, i) => {
            const keep = i === 0 || i === data.length - 1 || i % labelEvery === 0
            if (!keep) return null
            return (
              <text
                key={d.key}
                x={x(i)} y={H - 8} textAnchor="middle"
                className="fill-muted-foreground" style={{ fontSize: 11 }}
              >
                {d.shortLabel}
              </text>
            )
          })}
        </svg>
      </div>

      {/* One readout listing every series, so the pointer never has to land on
          a line to get a value. */}
      <div
        className={cn(
          'flex flex-wrap items-center gap-x-4 gap-y-1 rounded-lg border border-border bg-muted/30 px-3 py-2 text-xs transition-opacity',
          !active && 'opacity-60',
        )}
        role="status"
        aria-live="polite"
      >
        <span className="font-medium">
          {active
            ? `${active.label}${cumulative ? ' · to date' : ''}`
            : 'Hover a month'}
        </span>
        {SERIES.map((s) => (
          <span key={s.key} className="flex items-center gap-1.5">
            {/* A line key, not a filled box — at this density a box is
                data-weight ink doing a label's job. */}
            <span className="h-0.5 w-3 rounded-full" style={{ backgroundColor: s.color }} aria-hidden="true" />
            <span className="text-muted-foreground">{s.label}</span>
            <span className="font-medium tabular-nums">
              {active ? full(active[s.key]) : '—'}
            </span>
          </span>
        ))}
      </div>
    </div>
  )
}
