/**
 * Pure Stripe → Transaction mapper. No I/O — pass data in, get a plain object out.
 *
 * Revenue recognition convention (do NOT change without updating stripe-sync.ts):
 *   - chargeToTransaction  → income row for the gross charge amount
 *   - chargeFeeToTransaction → expense row for the Stripe processing fee
 *   - refundToTransaction  → expense row for the refunded amount
 *
 * Payouts and balance transfers are intentionally excluded. They represent
 * the same charge money moving to your bank account; counting them would
 * double revenue in the P&L totals.
 *
 * PCI: only card last4 and brand are stored. Full card numbers and raw bank
 * details are never persisted.
 */

import type Stripe from 'stripe'

// ─── Output shape ──────────────────────────────────────────────────────────────

export type StripeTransactionData = {
  ownerId: string
  type: 'income' | 'expense'
  source: 'stripe'
  amount: number           // always positive, in account currency units (e.g. dollars)
  currency: string         // ISO lower-case, e.g. "usd"
  description: string | null
  category: string
  occurredAt: Date
  clientId: null           // set later by the sync engine via email matching
  externalId: string       // Stripe object id or compound key (charge.id + ":fee")
  externalType: 'charge' | 'fee' | 'refund' | 'invoice'
  isRecurring: boolean     // true when the income comes from a Stripe Subscription
  /** Which subscription billed it, when the payload said. Null otherwise. */
  stripeSubscriptionId: string | null
  metadata: Record<string, unknown>
}

// ─── Subscription detection ───────────────────────────────────────────────────

/**
 * Returns true when a charge was generated by a Stripe Subscription.
 * Requires charge.invoice to be expanded (not just a string ID).
 *
 * Detection rule: invoice.billing_reason starts with "subscription".
 * Values that indicate subscription billing:
 *   subscription_create | subscription_cycle | subscription_update | subscription_threshold
 * Values that indicate one-off billing:
 *   manual | upcoming | null
 *
 * When invoice is not expanded (still a string), we conservatively return false.
 * The next backfill (which expands invoices) will correct the flag.
 */
function invoiceIsSubscription(inv: string | Stripe.Invoice | null | undefined): boolean {
  if (!inv) return false
  // String ID (unexpanded): presence of any invoice on a charge means Stripe generated
  // it — effectively always a subscription in practice.
  if (typeof inv === 'string') return true
  const invoice = inv as Stripe.Invoice & { subscription?: string | null }
  if (typeof invoice.billing_reason === 'string' && invoice.billing_reason.startsWith('subscription')) return true
  // billing_reason can be null on older invoices; fall back to subscription field.
  return !!invoice.subscription
}

/** The subscription id on an expanded invoice, when it carries one. */
function invoiceSubscriptionId(
  inv: string | Stripe.Invoice | null | undefined,
): string | null {
  if (!inv || typeof inv === 'string') return null
  const sub = (inv as Stripe.Invoice & { subscription?: string | Stripe.Subscription | null })
    .subscription
  if (!sub) return null
  return typeof sub === 'string' ? sub : sub.id
}

/**
 * Which subscription billed this charge, when one did.
 *
 * Recorded so a later cancellation can find the standing charges it created and
 * end them. `isSubscriptionCharge` answers whether a charge recurs, but not
 * *which* subscription it belongs to — and without that, cancelling in Stripe
 * left every recurring row counting toward MRR with nothing to match on.
 *
 * Returns null when the invoice is unexpanded, since the id is genuinely not in
 * the payload. The backfill expands invoices and fills it in on the next pass;
 * a null here is missing information, never a claim that the charge is one-off.
 */
export function subscriptionIdOf(charge: Stripe.Charge): string | null {
  const directInv = (charge as unknown as { invoice?: string | Stripe.Invoice | null }).invoice
  const fromDirect = invoiceSubscriptionId(directInv)
  if (fromDirect) return fromDirect

  const pi = charge.payment_intent
  if (pi && typeof pi === 'object') {
    const piInv = (pi as unknown as { invoice?: string | Stripe.Invoice | null }).invoice
    const fromPi = invoiceSubscriptionId(piInv)
    if (fromPi) return fromPi
  }

  return null
}

export function isSubscriptionCharge(charge: Stripe.Charge): boolean {
  // Path A: charge.invoice — present in webhook payloads and older API versions.
  // Removed from the TS type in SDK v22 but still in the actual API response for
  // accounts on older API versions.
  const directInv = (charge as unknown as { invoice?: string | Stripe.Invoice | null }).invoice
  if (invoiceIsSubscription(directInv)) return true

  // Path B: charge.payment_intent.invoice — the canonical path in Stripe API
  // versions 2022-11-15+ (codename versions like 2026-05-27.dahlia).
  // Requires expand: ['data.payment_intent.invoice'] in the charges.list call.
  const pi = charge.payment_intent
  if (pi && typeof pi === 'object') {
    const piInv = (pi as unknown as { invoice?: string | Stripe.Invoice | null }).invoice
    if (invoiceIsSubscription(piInv)) return true
  }

  return false
}

// ─── Type guards for expanded objects ─────────────────────────────────────────

function isExpandedBalanceTx(
  bt: Stripe.Charge['balance_transaction'],
): bt is Stripe.BalanceTransaction {
  return typeof bt === 'object' && bt !== null && 'fee' in bt
}

export function isExpandedCustomer(
  c: Stripe.Charge['customer'],
): c is Stripe.Customer {
  return (
    typeof c === 'object' &&
    c !== null &&
    (c as { deleted?: unknown }).deleted !== true
  )
}

// ─── Counterparty extraction ──────────────────────────────────────────────────

function extractCounterparty(charge: Stripe.Charge): {
  name: string | null
  email: string | null
  stripeCustomerId: string | null
  last4: string | null
  brand: string | null
} {
  const billingName = charge.billing_details?.name ?? null
  const billingEmail = charge.billing_details?.email ?? null

  const customer = charge.customer
  const customerEmail = isExpandedCustomer(customer) ? (customer.email ?? null) : null
  const stripeCustomerId =
    typeof customer === 'string'
      ? customer
      : isExpandedCustomer(customer)
        ? customer.id
        : null

  // PCI: last4 and brand only — never card numbers or raw bank details
  const card = charge.payment_method_details?.card
  const last4 = card?.last4 ?? null
  const brand = card?.brand ?? null

  return {
    name: billingName,
    email: billingEmail ?? customerEmail,
    stripeCustomerId,
    last4,
    brand,
  }
}

// ─── Mappers ──────────────────────────────────────────────────────────────────

/**
 * Maps a succeeded Stripe charge to an income transaction row.
 * Amount is the gross charge (before Stripe fee deduction).
 */
/** The charge's payment intent id, whether it arrived expanded or as a string. */
export function paymentIntentId(charge: Stripe.Charge): string | null {
  const pi = charge.payment_intent
  if (typeof pi === 'string') return pi
  return pi?.id ?? null
}

export function chargeToTransaction(
  charge: Stripe.Charge,
  ownerId: string,
): StripeTransactionData {
  const counterparty = extractCounterparty(charge)
  const recurring = isSubscriptionCharge(charge)
  return {
    ownerId,
    type: 'income',
    source: 'stripe',
    amount: charge.amount / 100,
    currency: charge.currency.toLowerCase(),
    description: charge.description ?? null,
    category: 'Stripe payment',
    occurredAt: new Date(charge.created * 1000),
    clientId: null,
    // Keyed on the payment intent, not the charge.
    //
    // A client paying an invoice through the public link produces two webhooks
    // for one payment: checkout.session.completed, which
    // markInvoicePaidFromCheckout records against the payment intent, and
    // charge.succeeded, which lands here. The idempotency key is
    // (ownerId, source, externalId), so keying this on `ch_...` while the other
    // path used `pi_...` put the same money in Finance twice — and an invoice
    // payment is usually the largest number in the month.
    //
    // Charges made outside a PaymentIntent flow still key on their own id.
    externalId: paymentIntentId(charge) ?? charge.id,
    externalType: 'charge',
    isRecurring: recurring,
    stripeSubscriptionId: subscriptionIdOf(charge),
    metadata: {
      counterpartyName: counterparty.name,
      counterpartyEmail: counterparty.email,
      stripeCustomerId: counterparty.stripeCustomerId,
      last4: counterparty.last4,
      brand: counterparty.brand,
    },
  }
}

/**
 * Maps the Stripe processing fee for a charge to an expense transaction row.
 * Returns null when the balance_transaction is not expanded or fee is zero.
 *
 * Using a compound externalId (chargeId + ":fee") keeps the fee idempotently
 * linked to its source charge while satisfying the unique constraint.
 */
export function chargeFeeToTransaction(
  charge: Stripe.Charge,
  ownerId: string,
): StripeTransactionData | null {
  const bt = charge.balance_transaction
  if (!isExpandedBalanceTx(bt)) return null
  if (bt.fee <= 0) return null

  return {
    ownerId,
    type: 'expense',
    source: 'stripe',
    amount: bt.fee / 100,
    currency: charge.currency.toLowerCase(),
    description: `Stripe fee for ${charge.id}`,
    category: 'Stripe fees',
    occurredAt: new Date(charge.created * 1000),
    clientId: null,
    externalId: `${charge.id}:fee`,
    externalType: 'fee',
    isRecurring: isSubscriptionCharge(charge),  // mirrors the income row for the same charge
    stripeSubscriptionId: subscriptionIdOf(charge),
    metadata: {
      chargeId: charge.id,
      feeDetails: bt.fee_details ?? [],
    },
  }
}

/**
 * Maps a paid Stripe Invoice to an income row.
 *
 * Only call this when invoice.charge is null (no backing charge object).
 * When invoice.charge is set, charge.succeeded fires too — use chargeToTransaction
 * for that path and skip this mapper to avoid double-counting.
 */
export function invoiceToTransaction(
  invoice: Stripe.Invoice,
  ownerId: string,
): StripeTransactionData {
  const customerEmail =
    typeof invoice.customer_email === 'string' ? invoice.customer_email : null
  const customerName =
    typeof invoice.customer_name === 'string' ? invoice.customer_name : null
  const stripeCustomerId =
    typeof invoice.customer === 'string' ? invoice.customer : null

  return {
    ownerId,
    type: 'income',
    source: 'stripe',
    amount: invoice.amount_paid / 100,
    currency: invoice.currency.toLowerCase(),
    description: invoice.description ?? null,
    category: 'Stripe payment',
    occurredAt: new Date(invoice.created * 1000),
    clientId: null,
    externalId: invoice.id!,
    externalType: 'invoice',
    isRecurring: typeof invoice.billing_reason === 'string' &&
      invoice.billing_reason.startsWith('subscription'),
    stripeSubscriptionId: invoiceSubscriptionId(invoice),
    metadata: {
      counterpartyName: customerName,
      counterpartyEmail: customerEmail,
      stripeCustomerId,
      invoiceNumber: invoice.number ?? null,
    },
  }
}

/**
 * Maps a Stripe refund to an expense transaction row.
 *
 * Convention: refunds are recorded as expense rows (positive amount, type =
 * "expense"). Combined with the original income row they net to the correct
 * P&L effect: income $100 + expense $100 = $0 net for a full refund.
 */
export function refundToTransaction(
  refund: Stripe.Refund,
  charge: Stripe.Charge,
  ownerId: string,
): StripeTransactionData {
  return {
    ownerId,
    type: 'expense',
    source: 'stripe',
    amount: refund.amount / 100,
    currency: refund.currency.toLowerCase(),
    description: `Refund for ${charge.id}`,
    category: 'Other expense',
    occurredAt: new Date(refund.created * 1000),
    clientId: null,
    externalId: refund.id,
    externalType: 'refund',
    isRecurring: false,  // refunds are adjustments, never MRR
    stripeSubscriptionId: null,
    metadata: {
      chargeId: charge.id,
      reason: refund.reason ?? null,
    },
  }
}
